# Описание проекта

Необходимо выяснить на сколько минут ускоряет процесс сборки бака вырезка отверстий на плазменном станке.


# Задачи

По трем счетам выбраны баки для эксперимента.</br>

Один бак делается с отверстиями. Второй без. </br>

Затем баки необходимо дать на сборку на участок. Баки одного счета на сборку на один участок.</br>

Собрать с участков данные о затратах времени на работу согласно типам операций.</br>

Обработать данные и сравнить результаты.

# Описание результата

Были выбраны три счета и четыре участка для эксперимента.</br>

По счету 668 эксперимент прошел с соблюдением всех правил. </br>

По счету 686 эксперимент прошел частично с соблюдением правил.</br>

По счету 909 эксперимент проведен не корректно.</br>

In [1]:
# Загрузка баблиотек

import pandas as pd
import numpy as np

In [2]:
# Загрузка данных

bill_686 = pd.read_excel('D:/Киселев/Эксперимент по ускорению пр-ва/Результаты эксперимента.xlsx', sheet_name='686')
bill_668 = pd.read_excel('D:/Киселев/Эксперимент по ускорению пр-ва/Результаты эксперимента.xlsx', sheet_name='668')
bill_909 = pd.read_excel('D:/Киселев/Эксперимент по ускорению пр-ва/Результаты эксперимента.xlsx', sheet_name='909')
table = pd.read_excel('D:/Киселев/Доп инфа по счетам.xlsx')

In [3]:
# Информация по счетам

display(table[table['Номер счета'] == 668])
display(table[table['Номер счета'] == 686])
display(table[table['Номер счета'] == 909])

,Номер счета,Размеры бака,Положение,Материал,Элемент,Объем,Кол-во баков,Примечание
65,668,Ф800Х2031,Вертикальное,Нерж,Электро,1000,3,В работе

,Номер счета,Размеры бака,Положение,Материал,Элемент,Объем,Кол-во баков,Примечание
67,686,Ф600Х2197,Вертикальное,09Г2С,Электро,600,20,В работе

,Номер счета,Размеры бака,Положение,Материал,Элемент,Объем,Кол-во баков,Примечание
103,909,Ф800Х2031,Вертикальное,Нерж,Змеевик,1000,4,В работе

Для проведения эксперимента были выбраны по счетам следующее количество баков:

- 668 - 2 штуки
- 686 - 2 штуки
- 909 - 4 штуки

При этом по каждому счету бак с отвестиями сделан в одном экземпляре.

Для проведения эксперимента выбраны во втором цеху участки с первого по четвертый:

- 668 - участок 2/3 - оба бака
- 686 - участки 2/3 и 2/4 - по одному баку
- 909 - участки 2/1 и 2/2 - по два бака

In [4]:
# Вычисление разницы во времени сборки бака по счетам в минутах

print("По счету 686 ускорение составляет:", bill_686['Время операции.1'].sum() - bill_686['Время операции'].sum(),'минуты')
print("По счету 668 ускорение составляет:", bill_668['Время операции.1'].sum() - bill_668['Время операции'].sum(),'минут')
print("По счету 909 ускорение составляет:", bill_909['Время операции'].sum() - bill_909['Время операции.1'].sum(), 'и',
      bill_909['Время операции.2'].sum() - bill_909['Время операции.1'].sum(),'минут')

По счету 686 ускорение составляет: 132.0 минуты
По счету 668 ускорение составляет: 47.0 минут
По счету 909 ускорение составляет: 101.0 и 66.0 минут

Поскольку сравнивать необходимо разницу в работе по бакам на одном участке, а мы проводили часть эксперимента на двух разных участках, считаю полученные результаты не отражающими полную картину ускорения производства.</br>

По счету 668 - данные корректны.</br>

По счету 686 - данные с разных участков. Да, мы видим ускорение. Но оно не корректно. </br>

По счету 909 - ускорение внутри участка составило 101 минуту. Сранение с соседним участком, что делали сразу два бака получилось не таким сильным - 66 минут. Эта часть эксперимента не показывает полное время ускорения работ. Но показывает, что мы получили ускорение работы.